### ISSUE TITLE
SMK browser doesn't appear to download files

### ISSUE THREAD

**Issue by jpy-luke** [menu-hanke/smk-browser#14]
It appears that the application plain doesn't download files anymore. I suspect that the MML API is now no longer available as public beta. Must investigate by establishing the dev environment and debugging the program.

Material UI v4 seems to be a blocker for establishing dev environment. The project is partially using material UI v5 beta. This is causing an issue initializing the dev environment. Will need to investigate and fix this first.

Original description
```
SMK Browser not working.

Property ID, Version and Folder path all given.
Download: no response.

Logs in clipboard: undefined,

What's wrong?
```

**Comment by PauliSairanen** [comment]
We are investigating this also and have requested a new trial rights to test the new API from MML (Maanmittauslaitos). I will test and update the application once I´ll recieve the response from MML. Hopefully this is enough to fix the download issue.

Regarding the Material UI update and pipeline issues, those have been taken into account and will also be fixed afterwards.
